version: '3.8'
services:
  mysite:
    build: 
      context: ./mysite
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    volumes:
      - .:/app


 


      


 